name: Atualizador de Dados Fiscais

on:
  schedule:
    - cron: '0 9 * * 1' # Roda toda Segunda às 09:00 UTC (06:00 BRT)
  workflow_dispatch: # Botão para rodar manualmente

permissions:
  contents: write

jobs:
  update-data:
    runs-on: ubuntu-latest
    steps:
      - name: Baixar repositório
        uses: actions/checkout@v4

      - name: Configurar Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Instalar bibliotecas
        run: |
          pip install -r requirements.txt

      - name: Rodar Scraper
        run: python scraper.py

      - name: Salvar (Commit) mudanças
        run: |
          git config user.name "Robo Atualizador"
          git config user.email "actions@github.com"
          git add dados_fiscais.json
          timestamp=$(date -u)
          git commit -m "Atualizando dados fiscais: ${timestamp}" || exit 0
          git push